export const API_ERROR_CODE = {
  VALIDATION_ERROR: "VALIDATION_ERROR",

  DUPLICATE_EMAIL: "DUPLICATE_EMAIL",
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",

  INVALID_VERIFICATION_CODE: "INVALID_VERIFICATION_CODE",
  EXPIRED_VERIFICATION_CODE: "EXPIRED_VERIFICATION_CODE",
  EMAIL_VERIFICATION_NOT_FOUND: "EMAIL_VERIFICATION_NOT_FOUND",

  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  REQUIRED_TERMS_NOT_AGREED: "REQUIRED_TERMS_NOT_AGREED",
  INVALID_ACTIVITY_REGION: "INVALID_ACTIVITY_REGION",
  INVALID_INTEREST_CATEGORY_COUNT: "INVALID_INTEREST_CATEGORY_COUNT",

  REGION_NOT_FOUND: "REGION_NOT_FOUND",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  POSTING_NOT_FOUND: "POSTING_NOT_FOUND",
  BOOKMARK_DUPLICATE: "BOOKMARK_DUPLICATE",
  BOOKMARK_NOT_FOUND: "BOOKMARK_NOT_FOUND",
  PARTICIPATION_DUPLICATE: "PARTICIPATION_DUPLICATE",
  POSTING_APPLICATION_UNAVAILABLE: "POSTING_APPLICATION_UNAVAILABLE",
  MEETING_NOT_FOUND: "MEETING_NOT_FOUND",
  MEETING_BOOKMARK_DUPLICATE: "MEETING_BOOKMARK_DUPLICATE",
  MEETING_BOOKMARK_NOT_FOUND: "MEETING_BOOKMARK_NOT_FOUND",

  DUPLICATE_PHONE_NUMBER: "DUPLICATE_PHONE_NUMBER",
  DUPLICATE_NICKNAME: "DUPLICATE_NICKNAME",

  INVALID_LOGIN: "INVALID_LOGIN",

  SUSPENDED_USER: "SUSPENDED_USER",
  WITHDRAWN_USER: "WITHDRAWN_USER",

  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  EXPIRED_TOKEN: "EXPIRED_TOKEN",
  REVOKED_TOKEN: "REVOKED_TOKEN",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODE)[keyof typeof API_ERROR_CODE];
